import { Provider } from "react-redux";
import Footer from "../components/Footer";
import Navbar from "../components/ui/Navbar";
import Providers from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ASOS Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${inter.className} bg-mywhite`}>
          <Navbar />
          <div className="pl-10 pr-10 mx-auto">{children}</div>

          <Footer />
        </body>
      </Providers>
    </html>
  );
}
